### PR TITLE
Add option to enable/disable infinite slideshow

### PR DESCRIPTION
**Pull request by dpooley**
Adds the `infinite` property as an option in slideshow configuration, enabled by default.

### CODE REVIEW

**Comment by dpooley** [comment]
Hi @Dalvany, please let me know if there is anything missing from this PR and I'll fix it, thanks. (also, thanks for creating this great plugin!)

**Comment by Dalvany** [comment]
Hello @dpooley , thanks for the contribution !
Code seems fine, I'll try to run it this evening and merge it right away.

**Comment by Dalvany** [comment]
It's works nicely. I merge. Thanks again for the contribution.

**Comment by Dalvany** [comment]
Closes #65

**Comment by Dalvany** [comment]
I'll probably release in grafana this month but I'll wait a little in case there is some other thing to include.

**Pull request merged**
